Dev
PowenTseng/remote-assignments pull request #1
Opened 2023-09-30 06:46 UTC by PowenTseng

Observation for assignment 3:
<img width="600" alt="executionTime" src="https://github.com/PowenTseng/remote-assignments/assets/114264970/29427036-a023-401d-bcb9-6584eb58774b">
1. 在運行Synchronous functions時，thread會等待當前運行的程式完成後，才會運行接下來的程式；反之，在運行Asynchronous functions時，thread會讓需時較久的程式在背景執行，同時運行接下來的程式。
2. 當執行需時較久的程式時，像是打API跟資料庫取資料等，可以使用Asynchronous functions，如此才不會造成程式運行卡在這，可以繼續往下執行。
3. 
Callback functions: 
pro: 簡單直觀，可以用於處理簡單的Asynchronous processing。
con: 當處理較複雜的Asynchronous processing時。會產生callback hell，難以閱讀修改。

Promise:
pro: 可以解決callback hell的問題、可使用.catch進行錯誤處理。
con: 較為複雜

Async/await
pro: 程式更加簡單與結構化、可使用try/catch進行錯誤處理
con: 需要在async函數內部使用

Understanding check:
1. 
From local:
<img width="963" alt="connectedFromLocal" src="https://github.com/PowenTseng/remote-assignments/assets/114264970/a005c8f0-f2fe-4746-b778-2072d967bb05">
From EC2:
<img width="750" alt="connectedFromEc2" src="https://github.com/PowenTseng/remote-assignments/assets/114264970/42217303-4f72-4467-93ab-6774ad9cbc61">

2. 關掉重開EC2後，public IP會變。因為public IP預設是跟著instance的life cycle在走的，當關掉EC2，public IP會被釋放，重啟EC2後會被分配新的public IP。且public IP是有限的資源，因此當我們關掉EC2後，可以把這組IP給別的instance使用，做有效的利用。

3. 使用Elastic IP可以將IP綁定在這個instance上，使其不會受到EC2關閉重啟的影響。

Elastic IP address: 52.63.149.33
Database name: database-2
Change summary:
add readme
add two .js files 
answering questions in PR description

2023-09-30 11:38 UTC, addie-tyc requested changes
回答沒問題，但 assignment 3 需要印出執行 3 次 request 花費的總時間

2023-10-01 00:05 UTC, PowenTseng commented
> 回答沒問題，但 assignment 3 需要印出執行 3 次 request 花費的總時間

已經將修改後requestAsync.js跟requestSync.js push上來了，也重新截圖並更新在PR description了，感謝！

2023-10-01 02:33 UTC, addie-tyc commented
requestSync 沒問題，但 Async 的部分只有測到最後一個 function 的時間。
因為兩個檔案都只分別執行 3 次 request，不求精準的話可以直接用 time 這個指令測試檔案執行時間就好，可以想想如果需要在 code 裡面加上時間測定應該怎麼做？

2023-10-01 12:50 UTC, PowenTseng commented
> requestSync 沒問題，但 Async 的部分只有測到最後一個 function 的時間。 因為兩個檔案都只分別執行 3 次 request，不求精準的話可以直接用 time 這個指令測試檔案執行時間就好，可以想想如果需要在 code 裡面加上時間測定應該怎麼做？

目前有做修正，使用另一個function來確認三個async functions是否完成，當都完成後才print 出總執行時間，不太確定是不是老師所要求的？再麻煩老師幫我確認看看～

2023-10-01 16:25 UTC, addie-tyc approved these changes
改動有符合需求，沒問題！

2023-10-08 15:31 UTC, merged