to make a new PR
PowenTseng/remote-assignments pull request #2
Opened 2023-10-08 16:44 UTC by PowenTseng

備註：我不小心把之前的PR merge了，dev又沒有新的更動能push上來，所以有做了一些無謂的git commit，實際上的更動內容僅為換行之類的。另外就是我有些git commit message忘記按照要求的格式，之後我會多注意～

1. How did you design the user table schema? Why?
user table schema包含有關於使用者的基本資訊，包含id、name、email、password和created_at。
id：type需要為integer，且是整個table中不重複出現的資訊，也不會是NULL的column，所以他是primary key，且預設隨著使用者註冊會自動increment。

name：type為VARCHAR，可容納char，並有255個char的限制。另外因為每個用戶都要有name，所以也限定不能為NULL。\
email：type為VARCHAR，可容納char，並有255個char的限制。因為每個用戶都要有email，所以也限定不能為NULL。另外用戶間也不會有重複的email，所以是Unique的。
passwrod：type為VARCHAR，可容納char，並有60個char的限制。另外因為每個用戶都要有password，所以也限定不能為NULL。
created_at：type為TIMESTAMP，隨時記錄註冊時的時間。

2. What does the status code mean? Is it a must to use? 
HTTP status code是server在client向他發出request時發出的，代表server處理client request的結果，status code為三位數字，常見的包涵：
200：代表成功
400：Bad request（client端有誤）
401：Unauthorized（缺乏身份驗證）
403：Forbidden（拒絕授權）
404：Not Found（找不到請求的資源）
500：Internal Server Error

通常遇到4開頭的是代表前端有誤，500才是後端有錯。

Status code可以幫助client了解他們發送request的結果，提供一個標準化的語言讓client跟server可以進行良好的溝通。雖然仍然可以不使用Status code，但這樣會使的API更難以理解與使用。

3. How and what tools did you use to test your APIs?
我一開始在測試healthcheck的時候是用瀏覽器上去連localhost或是連Elastic IP，但後來需要測試user sign up的GET和POST request因為沒有寫好的前端，所以改使用postman去測試。

4. How and what tools did you use to make sure the app would not shut down even if you exit the ssh connection? 
我使用nodemon來確保app不會因為離開ssh連線而被關掉。使用方法為：在terminal輸入nodemon app.js，而不是原本的node app.js。

5. What are the interactions between client, firewall, EC2 and RDS when you send a request
當client發送一個request到部署在EC2上的網頁應用程式時，EC2會再跟RDS, firewall進行互動，最後再回傳response給client。

當client發送HTTP或HTTPS request取用網頁程式，request會被送到EC2 instance上的public IP。

request會需要透過security group的inbound rule，確認client的IP、port number和protocal是否合乎規定，最後會拒絕或准許這個request。被准許的request會被送到EC2 instance上。

EC2 instance接收request後，會由application server，如：Node.js，處理request。如果request 需要資料庫中的data，則會發送一個query到RDS instance請求資料，而這一步也會需要經過RDS的security group的inbound rule，有得到准許才能取用資料，包含SELECT、INSERT、UPDATE和DELETE。

EC2 instance接受到來自RDS的資料後，會進行處理並產生適當的response，常見的包含JSON格式的API response。把response回傳給client後，再看client怎麼處理這個response。

2023-10-09 04:12 UTC, addie-tyc commented
4. 我對 nodemon 的理解是他能夠自動偵測現在 app server 相關的檔案是否有變動，並根據變動自動 reload 檔案，讓你不用每次改動都要關掉重開，他還有讓你關掉 ssh 視窗之後讓 app 繼續運行的功能嗎？（真心疑惑）

2023-10-09 04:16 UTC, addie-tyc requested changes
能夠 access 服務的網址記得貼上來喔

2023-10-09 04:17 UTC, addie-tyc commented
另外，Request-Date 可以直接從 request header 裡面拿就行了，不用自己 new Date 喔

2023-10-10 16:26 UTC, PowenTseng commented
> 4. 我對 nodemon 的理解是他能夠自動偵測現在 app server 相關的檔案是否有變動，並根據變動自動 reload 檔案，讓你不用每次改動都要關掉重開，他還有讓你關掉 ssh 視窗之後讓 app 繼續運行的功能嗎？（真心疑惑）

歹勢是我沒搞清楚nodemon的用法，我現在是使用pm2來讓我的app在關掉ssh後繼續運行

2023-10-10 16:26 UTC, PowenTseng commented
> 能夠 access 服務的網址記得貼上來喔

52.63.149.33:3000

2023-10-10 16:34 UTC, PowenTseng commented
> 另外，Request-Date 可以直接從 request header 裡面拿就行了，不用自己 new Date 喔

已修正，感謝提醒！

2023-10-11 01:18 UTC, addie-tyc commented
實測還是沒有更動喔
<img width="1010" alt="截圖 2023-10-11 09 14 00" src="https://github.com/PowenTseng/remote-assignments/assets/65952631/f65f5ede-909f-46a7-8a32-f48155823b3c">
<img width="1007" alt="截圖 2023-10-11 09 14 08" src="https://github.com/PowenTseng/remote-assignments/assets/65952631/762c56ae-a42c-4503-94b8-8a3fbf6ac780">

2023-10-11 01:51 UTC, PowenTseng commented
> 實測還是沒有更動喔 <img alt="截圖 2023-10-11 09 14 00" width="1010" src="https://user-images.githubusercontent.com/65952631/274112201-f65f5ede-909f-46a7-8a32-f48155823b3c.png"> <img alt="截圖 2023-10-11 09 14 08" width="1007" src="https://user-images.githubusercontent.com/65952631/274112266-762c56ae-a42c-4503-94b8-8a3fbf6ac780.png">

好像是我在EC2上git pull 之後忘記重開pm2了，但我也不太確定我做的是不是對的，下圖一是我在ec2上用vim開app.js，應該是有改正從request header 裡面拿，但我用我的postman測（如下圖二），Headers裡面沒有Request-Date這一項，想請問一下這是要在postman自己手動新增上去的嗎？

<img width="715" alt="Screenshot 2023-10-11 at 9 45 17 AM" src="https://github.com/PowenTseng/remote-assignments/assets/114264970/57cb83c1-7017-4098-a2ea-7d5c5c98dbe1">

![Screenshot 2023-10-11 at 9 49 58 AM](https://github.com/PowenTseng/remote-assignments/assets/114264970/8b190cf3-f352-48b0-a986-cb025451bc82)

2023-10-11 06:28 UTC, addie-tyc commented
是的，發出 request 的時候也要符合 API 文件的規範喔！

2023-10-13 02:49 UTC, addie-tyc approved these changes
LGTM

2023-10-14 06:37 UTC, merged